# Generated by Django 5.2.1 on 2025-05-21 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scolarite.classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarite.matiere'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarite.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarite.etudiant')),
            ],
        ),
    ]
