# Generated by Django 5.0.1 on 2025-06-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0002_remove_etudiant_matricule_remove_etudiant_telephone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='note',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('DEVOIR', 'Devoir'), ('CONTROLE', 'Contrôle'), ('EXAMEN', 'Examen')], default='DEVOIR', max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarite.classe'),
        ),
    ]
