# Generated by Django 5.0.1 on 2025-06-10 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0004_alter_etudiant_options_etudiant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
